name: CI/CD Webhook Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Config .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore --configuration Release

      - name: run Tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t webhook-service -f WebhookService.Api/Dockerfile WebhookService.Api/

      - name: Tag Docker Image
        run: docker tag webhook-service ${{ secrets.DOCKER_USERNAME }}/webhook-service:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/webhook-service:latest
